Improving nnUNet inference speed
MIC-DKFZ/nnUNet pull request #2048
Opened 2024-03-28 20:49 UTC by ancestor-mithril

Main additions are:
* Using `torch.backends.cudnn.benchmark = True` (used during training, but forgot during inference).
* Replacing `torch.no_grad` context with a single `torch.inference_mode` context.
* Using inplace operations for calculating and using the gaussian.

2024-04-09 17:35 UTC, FabianIsensee requested changes

2024-04-10 09:39 UTC, ancestor-mithril commented on nnunetv2/inference/predict_from_raw_data.py
> +                n_predictions = torch.zeros(data.shape[1:], dtype=torch.half, device=results_device)
I see. Somehow, I failed to see the usage of `n_predictions` outside of the `self.use_gaussian` context. 
I'll fix this.

2024-04-10 09:42 UTC, ancestor-mithril commented on nnunetv2/inference/sliding_window_prediction.py
> +@lru_cache(maxsize=None)
Ok, I got this. Normally, `compute_gaussian` should be called with the same parameters so only 1 or 2 values would be in the cache.

2024-04-11 13:30 UTC, merged

2024-04-11 13:32 UTC, FabianIsensee commented
Thanks! Had to make two small changes to make sure everything works + yields the same results.
What would you say is the advantage of `@torch.inference_mode()` over `with torch.no_grad()`? Prediction speed seems to be the same

2024-04-11 13:58 UTC, ancestor-mithril commented
Tensors created during inference mode are slimmer because they do not have a version counter and requires_grad can't be set to True anymore. More information here: https://stackoverflow.com/a/74197846/18441695.
In my tests,  `@torch.inference_mode()` is slightly less than 1% faster than `no_grad` for nnUNet.